#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.menu"
CFG="$HOME/.config/eww/menu"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many \
		   system \
		   apps \
       power \
		   folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
					system apps power folders
	rm "$FILE"
fi
